# Generated by Django 3.1.4 on 2021-02-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210208_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('student', 'student'), ('worker', 'worker')], default='', max_length=8, verbose_name='직업'),
        ),
    ]
