# Generated by Django 3.1.6 on 2021-02-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='subject',
            field=models.CharField(choices=[('프로그래밍', '프로그래밍'), ('자격증', '자격증'), ('기타', '기타')], default='', max_length=16, verbose_name='항목'),
        ),
    ]
