# Generated by Django 3.1.6 on 2021-02-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20210219_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='', max_length=150, verbose_name='댓글'),
        ),
    ]
